require: 
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion:  3.0.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleDescribes:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false