require: 
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion:  3.0.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false
  Max: 5
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleDescribes:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
